apiVersion: v1
kind: Pod
metadata:
  name: {{ quote .Values.manager_name}}
  labels:
    app: {{ quote .Values.rstudio_app_name}}
spec:
  containers:
    - name: {{ quote .Values.manager_name}}
      image: {{ .Values.customImage.repository}}
      tag: {{ .Values.customImage.tag}}
      env:
        - name: {{ .Values.customImageEnv.name}}
          value: {{ quote .Values.customImageEnv.value}}
      ports:
        - containerPort: {{ .Values.customImage.containerPort}}
      command: ["/init"]
      imagePullPolicy: {{ .Values.customImage.pullPolicy}}
  restartPolicy: "OnFailure"
