apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis_app_name }}
spec:
  ports:
    - port: {{ .Values.redisImage.containerPort}}
      targetPort: {{ .Values.redisImage.containerPort}}
  selector:
    app: {{ .Values.redis_app_name }}
