apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rstudio_app_name}}
  labels:
    app: {{ .Values.rstudio_app_name}}
spec:
  type: {{ .Values.customImageService.type}}
  ports:
    - port: {{ .Values.customImageService.port}}
      nodePort: {{ .Values.customImageService.nodePort}}
      name: {{.Values.customImageService.name}}
  selector:
    app: {{ .Values.rstudio_app_name}}
